# Crawl news and legislation every Tuesday and Saturday at 9 AM
crawl_news_job:
  cron: "0 9 * * 2,6"  # At 09:00 on Tuesday and Saturday
  class: "CrawlNewsJob"
  queue: "default"
  args: []

crawl_legislation_job:
  cron: "30 9 * * 2,6"  # At 09:30 on Tuesday and Saturday
  class: "CrawlLegislationJob"
  queue: "default"
  args: []

# Generate scripts twice daily
generate_script_job:
  cron: "0 10,22 * * *"  # At 10:00 and 22:00 every day
  class: "GenerateScriptJob"
  queue: "default"
  args: [null, null]  # Pass null for both news_id and legislation_id to process pending

# Produce videos twice daily
produce_video_job:
  cron: "0 11,23 * * *"  # At 11:00 and 23:00 every day
  class: "ProduceVideoJob"
  queue: "default"
  args: []

# Upload videos twice daily
upload_video_job:
  cron: "30 11,23 * * *"  # At 11:30 and 23:30 every day
  class: "UploadVideoJob"
  queue: "default"
  args: []

crawl_news:
  cron: "0 */4 * * *"  # Every 4 hours
  class: "CrawlNewsJob"
  queue: default
  description: "Crawl news sources for election fraud related content"

crawl_legislation:
  cron: "0 0 * * *"  # Daily at midnight
  class: "CrawlLegislationJob"
  queue: default
  description: "Analyze new election-related legislation"

generate_script:
  cron: "30 */4 * * *"  # Every 4 hours, 30 minutes after news crawl
  class: "GenerateScriptJob"
  queue: default
  description: "Generate script for new content"

produce_video:
  cron: "0 */6 * * *"  # Every 6 hours
  class: "ProduceVideoJob"
  queue: default
  description: "Produce video from generated script"

upload_video:
  cron: "30 */6 * * *"  # Every 6 hours, 30 minutes after video production
  class: "UploadVideoJob"
  queue: default
  description: "Upload produced video to YouTube" 