# Crawl news and legislation every Tuesday and Saturday at 9 AM
crawl_news_job:
  cron: "0 9 * * 2,6"  # At 09:00 on Tuesday and Saturday
  class: "CrawlNewsJob"
  queue: "default"
  args: []

crawl_legislation_job:
  cron: "30 9 * * 2,6"  # At 09:30 on Tuesday and Saturday
  class: "CrawlLegislationJob"
  queue: "default"
  args: []

# Generate scripts twice daily
generate_script_job:
  cron: "0 10,22 * * *"  # At 10:00 and 22:00 every day
  class: "GenerateScriptJob"
  queue: "default"
  args: [null, null]  # Pass null for both news_id and legislation_id to process pending

# Produce videos twice daily
produce_video_job:
  cron: "0 11,23 * * *"  # At 11:00 and 23:00 every day
  class: "ProduceVideoJob"
  queue: "default"
  args: []

# Upload videos twice daily
upload_video_job:
  cron: "30 11,23 * * *"  # At 11:30 and 23:30 every day
  class: "UploadVideoJob"
  queue: "default"
  args: [] 