:concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", 5) %>
:timeout: 8
:max_retries: 3

:queues:
  - [critical, 3]
  - [default, 2]
  - [low, 1]

development:
  :concurrency: 2

staging:
  :concurrency: 3

production:
  :concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", 10) %> 